import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Users table
  users: defineTable({
    backup_code_enabled: v.boolean(),
    banned: v.boolean(),
    clerk_id: v.string(),
    create_organization_enabled: v.boolean(),
    create_organizations_limit: v.optional(v.float64()),
    created_at: v.float64(),
    delete_self_enabled: v.boolean(),
    email_addresses: v.array(
      v.object({
        created_at: v.float64(),
        email_address: v.string(),
        id: v.string(),
        linked_to: v.array(v.any()),
        matches_sso_connection: v.boolean(),
        object: v.string(),
        reserved: v.boolean(),
        updated_at: v.float64(),
        verification: v.object({
          attempts: v.null(),
          expire_at: v.null(),
          object: v.string(),
          status: v.string(),
          strategy: v.string(),
        }),
      })
    ),
    enterprise_accounts: v.array(v.any()),
    external_accounts: v.array(v.any()),
    external_id: v.null(),
    first_name: v.string(),
    has_image: v.boolean(),
    id: v.string(),
    image_url: v.string(),
    last_active_at: v.null(),
    last_name: v.string(),
    last_sign_in_at: v.null(),
    legal_accepted_at: v.null(),
    locale: v.null(),
    locked: v.boolean(),
    lockout_expires_in_seconds: v.null(),
    mfa_disabled_at: v.null(),
    mfa_enabled_at: v.null(),
    object: v.string(),
    passkeys: v.array(v.any()),
    password_enabled: v.boolean(),
    phone_numbers: v.array(v.any()),
    primary_email_address_id: v.string(),
    primary_phone_number_id: v.null(),
    primary_web3_wallet_id: v.null(),
    private_metadata: v.object({}),
    profile_image_url: v.string(),
    public_metadata: v.object({}),
    saml_accounts: v.array(v.any()),
    totp_enabled: v.boolean(),
    two_factor_enabled: v.boolean(),
    unsafe_metadata: v.object({}),
    updated_at: v.float64(),
    username: v.string(),
    verification_attempts_remaining: v.float64(),
    web3_wallets: v.array(v.any()),
    organization_ids: v.optional(v.array(v.string())),
  }),

  brokers: defineTable({
    org_id: v.string(),
    address: v.string(),
    address_2: v.union(v.null(), v.string()),
    docket_number: v.string(),
    email: v.union(v.null(), v.string()),
    image_url: v.union(v.null(), v.string()),
    name: v.string(),
    notes: v.union(v.null(), v.string()),
    phone: v.union(v.null(), v.string()),
    status: v.string(),
    usdot_number: v.string(),
    website: v.union(v.null(), v.string()),
  }).index("by_orgId", ["org_id"]),

  brokers_agents: defineTable({
    org_id: v.string(),
    broker_id: v.string(),
    email: v.string(),
    name: v.string(),
    phone: v.string(),
    position: v.null(),
  }).index("by_orgId", ["org_id"]),

  chats: defineTable({
    lastMessageId: v.optional(v.id("messages")),
    participantsIds: v.array(v.id("users")),
    type: v.string(),
    org_id: v.string(),
  }).index("by_orgId", ["org_id"]),

  drivers: defineTable({
    org_id: v.string(),
    email: v.null(),
    image_url: v.string(),
    license_number: v.string(),
    license_url: v.union(v.null(), v.string()),
    name: v.string(),
    phone: v.string(),
    status: v.string(),
  }).index("by_orgId", ["org_id"]),

  equipment: defineTable({
    org_id: v.string(),
    equipment_length: v.union(v.null(), v.string()),
    equipment_number: v.string(),
    equipment_type: v.string(),
    image_url: v.union(v.null(), v.string()),
    status: v.string(),
  }).index("by_orgId", ["org_id"]),

  counters: defineTable({
    org_id: v.string(),
    last_number: v.number(),
  }).index("by_org", ["org_id"]),

  loads: defineTable({
    org_id: v.string(),
    agent_id: v.optional(v.string()),
    broker_id: v.string(),
    commodity: v.string(),
    docs: v.array(v.string()),
    equipment_id: v.string(),
    instructions: v.union(v.null(), v.string()),
    invoice_number: v.string(),
    invoiced_at: v.optional(v.string()),
    length_ft: v.float64(),
    load_number: v.string(),
    load_status: v.string(),
    load_type: v.string(),
    paid_at: v.union(v.null(), v.string()),
    payment_terms_id: v.string(),
    progress: v.float64(),
    rate: v.number(),
    truck_id: v.string(),
    drivers: v.optional(v.array(v.string())),
  }).index("by_orgId", ["org_id"]),

  messages: defineTable({
    chatId: v.id("chats"),
    deliveredTo: v.array(v.id("users")),
    seenBy: v.array(v.id("users")),
    senderId: v.id("users"),
    text: v.string(),
  }),

  payment_terms: defineTable({
    org_id: v.string(),
    broker_id: v.string(),
    days_to_pay: v.float64(),
    email: v.union(v.null(), v.string()),
    fee_percent: v.number(),
    is_quickpay: v.boolean(),
    name: v.string(),
  }).index("by_orgId", ["org_id"]).index("by_brokerId", ["broker_id"]),

  stops: defineTable({
    org_id: v.string(),
    appointment_time: v.union(v.null(), v.string()),
    load_id: v.string(),
    location: v.string(),
    time_type: v.string(),
    type: v.string(),
    window_end: v.union(v.null(), v.string()),
    window_start: v.union(v.null(), v.string()),
  }).index("by_orgId", ["org_id"]).index("by_loadId", ["load_id"]),

  truck_inspections: defineTable({
    org_id: v.string(),
    inspection_date: v.string(),
    inspection_type: v.string(),
    notes: v.null(),
    result: v.string(),
    truck_id: v.string(),
  }).index("by_orgId", ["org_id"]),

  trucks: defineTable({
    org_id: v.string(),
    color: v.null(),
    docs: v.array(v.string()),
    driver_id: v.null(),
    image_url: v.string(),
    make: v.string(),
    model: v.string(),
    status: v.string(),
    transponder_id: v.null(),
    truck_alias: v.union(v.null(), v.string()),
    truck_number: v.string(),
    vin: v.string(),
    year: v.union(v.null(), v.float64()),
  }).index("by_orgId", ["org_id"]),
});
